name: youtube_player_flutter
description: Flutter plugin for playing or streaming inline YouTube videos using the official iFrame player API. This plugin supports both Android and iOS.
version: 7.0.0+7
repository: https://github.com/sarbagyastha/youtube_player_flutter
homepage: https://github.com/sarbagyastha/youtube_player_flutter/tree/master/packages/youtube_player_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.1'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: 5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/speedometer.webp